### ISSUE TITLE
Huge stutters with Fix Shadow Buffer Bug enabled in some locations

### ISSUE THREAD

**Issue by KainXVIII** [Lyall/SO4Fix#1]
For example on the starting ship its almost unplayable due to stutters https://steamcommunity.com/id/KainXVIII/screenshot/2490008795920642225/ (you need to turn camera or start moving)
but as soon as you land on the first planet stutters are gone, weird!

**Comment by Lyall** [comment]
It sounds like you might be running short on VRAM and it's thrashing system RAM. Enabling proper 4K shadows will incur a decent increase in VRAM usage. It's unlikely that the fix itself is causing the issue since all it does is change the upper limit on shadow resolution.

I also can't replicate the issue as I did not experience this in the first few hours of gameplay with it enabled.

**Comment by KainXVIII** [comment]
> It sounds like you might be running short on VRAM and it's thrashing system RAM. Enabling proper 4K shadows will incur a decent increase in VRAM usage. It's unlikely that the fix itself is causing the issue since all it does is change the upper limit on shadow resolution.
> 
> I also can't replicate the issue as I did not experience this in the first few hours of gameplay with it enabled.

Yes, probably i'm low on ram/vram..
